create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null,
    username varchar(255) not null unique,
    is_admin boolean not null default false,
    token_version integer not null default 0
);

create table if not exists categories (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    slug varchar(255) not null unique
);

create table if not exists posts (
    id bigint generated by default as identity primary key,
    content text not null,
    created_at timestamp without time zone,
    likes integer not null,
    title varchar(255) not null,
    user_id bigint not null,
    slug varchar(255) not null unique,
    thumbnail varchar(2048),
    category_id bigint
);

create table if not exists comments (
    id bigint generated by default as identity primary key,
    content text not null,
    created_at timestamp without time zone,
    post_id bigint not null,
    user_id bigint not null
);

create table if not exists post_likes (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    post_id bigint not null,
    constraint post_likes_user_post_key unique (user_id, post_id)
);

alter table posts
    drop constraint if exists posts_user_id_fkey;

alter table posts
    add constraint posts_user_id_fkey
    foreign key (user_id) references users(id)
    on delete cascade;

alter table posts
    drop constraint if exists posts_category_id_fkey;

alter table posts
    add constraint posts_category_id_fkey
    foreign key (category_id) references categories(id)
    on delete set null;

alter table comments
    drop constraint if exists comments_post_id_fkey;

alter table comments
    add constraint comments_post_id_fkey
    foreign key (post_id) references posts(id)
    on delete cascade;

alter table comments
    drop constraint if exists comments_user_id_fkey;

alter table comments
    add constraint comments_user_id_fkey
    foreign key (user_id) references users(id)
    on delete cascade;

alter table post_likes
    drop constraint if exists post_likes_post_id_fkey;

alter table post_likes
    add constraint post_likes_post_id_fkey
    foreign key (post_id) references posts(id)
    on delete cascade;

alter table post_likes
    drop constraint if exists post_likes_user_id_fkey;

alter table post_likes
    add constraint post_likes_user_id_fkey
    foreign key (user_id) references users(id)
    on delete cascade;

create index if not exists idx_posts_created_at
    on posts (created_at desc);

create index if not exists idx_posts_user_created_at
    on posts (user_id, created_at desc);

create index if not exists idx_posts_category_created_at
    on posts (category_id, created_at desc);

create index if not exists idx_comments_post_created_at
    on comments (post_id, created_at desc);

create index if not exists idx_comments_user_id
    on comments (user_id);

create index if not exists idx_post_likes_post_id
    on post_likes (post_id);
