create table if not exists tags (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    slug varchar(255) not null unique,
    post_count integer not null default 0,
    created_at timestamp without time zone not null default now()
);

create table if not exists post_tags (
    post_id bigint not null,
    tag_id bigint not null,
    constraint post_tags_post_tag_key unique (post_id, tag_id),
    constraint post_tags_post_id_fkey foreign key (post_id) references posts(id) on delete cascade,
    constraint post_tags_tag_id_fkey foreign key (tag_id) references tags(id) on delete cascade
);

create table if not exists follows (
    id bigint generated by default as identity primary key,
    follower_id bigint not null,
    following_id bigint not null,
    created_at timestamp without time zone not null default now(),
    constraint follows_follower_following_key unique (follower_id, following_id),
    constraint follows_no_self_follow check (follower_id <> following_id),
    constraint follows_follower_id_fkey foreign key (follower_id) references users(id) on delete cascade,
    constraint follows_following_id_fkey foreign key (following_id) references users(id) on delete cascade
);

alter table users add column if not exists display_name varchar(255);
alter table users add column if not exists bio varchar(500);
alter table users add column if not exists avatar_url varchar(2048);
alter table users add column if not exists website varchar(512);
alter table users add column if not exists location varchar(255);
alter table users add column if not exists joined_at date;
alter table users add column if not exists follower_count integer not null default 0;
alter table users add column if not exists following_count integer not null default 0;
alter table posts add column if not exists status varchar(20);
alter table posts add column if not exists summary varchar(500);
alter table posts add column if not exists view_count integer not null default 0;
alter table posts add column if not exists comment_count integer not null default 0;
alter table posts add column if not exists updated_at timestamp without time zone;
alter table posts add column if not exists read_time varchar(50);

update posts
set status = 'PUBLISHED'
where status is null;

alter table posts
    alter column status set not null;

update users
set display_name = username
where display_name is null;

update users
set joined_at = current_date
where joined_at is null;

create index if not exists idx_post_tags_post_id
    on post_tags(post_id);

create index if not exists idx_post_tags_tag_id
    on post_tags(tag_id);

create index if not exists idx_follows_follower_id
    on follows(follower_id);

create index if not exists idx_follows_following_id
    on follows(following_id);

create index if not exists idx_posts_status_created_at
    on posts(status, created_at desc);

create index if not exists idx_tags_post_count
    on tags(post_count desc);

create table if not exists user_interests (
    user_id bigint not null,
    interest varchar(100) not null,
    constraint user_interests_user_interest_key unique (user_id, interest),
    constraint user_interests_user_id_fkey foreign key (user_id) references users(id) on delete cascade
);

create index if not exists idx_user_interests_interest
    on user_interests(interest);
