create table if not exists admin_action_logs (
    id bigint generated by default as identity primary key,
    actor_username varchar(255) not null,
    action varchar(80) not null,
    target_type varchar(80) not null,
    target_id bigint,
    details varchar(1000),
    created_at timestamp without time zone not null default now()
);

create index if not exists idx_admin_action_logs_created_at
    on admin_action_logs(created_at desc);
